version: '3.8'  # Compose file format version

services:
  web:
    build: .             # Build image from Dockerfile in current dir
    ports:
      - "3000:3000"       # Host:Container port
    volumes:
      - .:/app           # Mount local code to container
    depends_on:
      - db               # Wait for db before starting

  db:
    image: postgres:15   # Use official Postgres image
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
